PLAT-93 Implement deploy_id, enhance deploy_id restrictions
dominodatalab/terraform-azure-aks pull request #30
Opened 2022-09-07 14:21 UTC by miguelhar

2022-09-07 15:12 UTC, miguelhar commented on variables.tf
> +    condition     = length(var.deploy_id) >= 3 && length(var.deploy_id) <= 24 && can(regex("^([a-z][-a-z0-9]*[a-z0-9])$", var.deploy_id))
I intend to adjust the deployer:

- Adjust the module versions(AKS,GKE)
- Increase the the max_length to 20(to accommodate GKE).

2022-09-07 21:56 UTC, fraenkel requested changes

2022-09-07 21:56 UTC, fraenkel commented on tests/test.tf
> +  # }
why is this commented out?

2022-09-08 16:05 UTC, miguelhar commented on tests/test.tf
> +  # }
oops

2022-09-08 17:12 UTC, fraenkel approved these changes

2022-09-08 22:40 UTC, merged